//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones
    {
        public int Id { get; set; }
        public int IdMateria { get; set; }
        public int MatriculaAlumno { get; set; }
        public decimal Calificacion { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Materias Materias { get; set; }
    }
}
